kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: c1-svm1-nvme-pvc-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: c1-svm1-nvme-sc
