apiVersion: v1
kind: Secret
metadata:
  name: c1-svm1-backend-secret
  namespace: trident
type: kubernetes.io/basic-auth
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c1-svm1-san-backend
  namespace: trident
spec:
  version: 1
  backendName: ontap-san-backend
  storageDriverName: ontap-san
  managementLIF: 192.168.0.40
  dataLIF: 192.168.0.41
  svm: svm1
  credentials:
    name: c1-svm1-backend-secret