apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c1-svm1-nvme-tbc
  namespace: trident
spec:
  version: 1
  backendName: ontap-nvme-tbc
  storageDriverName: ontap-san
  managementLIF: 192.168.0.40
  dataLIF: 192.168.0.43
  svm: svm1
  sanType: nvme
  useREST: true
  credentials:
    name: san-backend-secret