kind: Pod
apiVersion: v1
metadata:
  name: san-pod
  namespace: default
  labels:
    app: san-web
spec:
  volumes:
    - name: san-storage
      persistentVolumeClaim:
       claimName: c1-svm1-iscsi-pvc-1
  containers:
    - name: san-container
      image: nginx:1.25-alpine-slim
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: san-storage