kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: san-basic
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: san-basic