---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: exechook
  labels:
    {{- include "tridentprotect.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
