{{- if not .Values.scc.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: trident-protect-job-erase
    namespace: {{ .Release.Namespace }}  
rules:
  - apiGroups:
      - ""
    resources:
      - "persistentvolumeclaims"
    verbs:
      - "get"
      - "list"
      - "create"
      - "update"
      - "patch"
      - "delete"

{{- end }}