{{- if .Values.scc.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: trident-protect-job-erase
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - "security.openshift.io"
    resourceNames:
      - {{ .Values.scc.name }}
    resources:
      - "securitycontextconstraints"
    verbs:
      - "use"
{{- end }}