{{- if .Values.scc.create }}
kind: SecurityContextConstraints
metadata:
  name: {{ .Values.scc.name }}
  labels:
    app.netapp.io/managed-by: protect.trident.netapp.io
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
  - DAC_READ_SEARCH
  - DAC_OVERRIDE
  - CHOWN
apiVersion: security.openshift.io/v1
fsGroup:
  type: RunAsAny
groups: []
priority: {{ .Values.scc.priority }}
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
users: []
volumes:
  - configMap
  - downwardAPI
  - emptyDir
  - persistentVolumeClaim
  - projected
  - secret
{{- end }}
