---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: resourcedelete
  labels:
    {{- include "tridentprotect.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - '*'
  verbs:
  - delete
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - delete
  - use
