---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: resourcesummaryupload
  labels:
    {{- include "tridentprotect.labels" . | nindent 4 }}
rules:
- nonResourceURLs:
  - '*'
  verbs:
  - get
  - list
  - use
