apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: mysqlapp-backuprestore1
  namespace: mysqlapp
spec:
  appArchivePath: mysqlapp_6a7fd6ca-24b0-4e84-bcb8-4e39049f1819/backups/mysqlapp-bkup-1_d62380c4-8d1e-4262-b90b-8d200a5c35f5
  appVaultRef: c1-svm0-s3-av
  namespaceMapping:
  - source: mysqlapp
    destination: mysqlapp2
---
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: mysqlapp2
  namespace: mysqlapp2
spec:
  includedNamespaces:
  - labelSelector: {}
    namespace: mysqlapp2