apiVersion: v1
kind: Secret
metadata:
  name: c1-svm0-backend-secret
  namespace: trident
type: kubernetes.io/basic-auth
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c1-svm0-nfs-tbc
  namespace: trident
spec:
  version: 1
  backendName: c1-svm0-nfs-tbe 
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.30
  dataLIF: 192.168.0.31
  svm: svm0
  credentials:
    name: c1-svm0-backend-secret