kind: Pod
apiVersion: v1
metadata:
  name: nfs-pod
  namespace: default
  labels:
    app: nfs-web
spec:
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
       claimName: c1-svm0-nfs-pvc-1
  containers:
    - name: nfs-container
      image: nginx:1.25-alpine-slim
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nfs-storage