apiVersion: protect.trident.netapp.io/v1
kind: SnapshotInplaceRestore
metadata:
  name: snapshotipr-mysql
  namespace: trident-protect
spec:
  appVaultRef: c1-s3-src-appvault
  appArchivePath: change_me