apiVersion: protect.trident.netapp.io/v1
kind: AppMirrorRelationship
metadata:
  name: testvm-dst-amr
  namespace: testvm-dst
spec:
  desiredState: Established
  destinationAppVaultRef: c2-svmdst-s3-av
  namespaceMapping:
  - destination: testvm-dst
    source: testvm
  recurrenceRule: |-
    DTSTART:20220101T000200Z
    RRULE:FREQ=MINUTELY;INTERVAL=5
  sourceAppVaultRef: c1-svmsrc-s3-av
  sourceApplicationName: testvm
  sourceApplicationUID: 43a57ec4-ca84-45e8-8559-75ffb7f276a8
  storageClassName: nfs-custom-sc