apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-custom-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.trident.netapp.io
parameters:
  storagePools: "c1-svm0-nfs-custom-tbe:.*"
  backendType: ontap-nas