---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: c1-svm0-nfs-custom-pvc-1-snapimport-1
  namespace: default
spec:
  # volumeSnapshotClassName: csi-snapclass (not required for pre-provisioned or imported snapshots)
  source:
    volumeSnapshotContentName: snapcontent-c1-svm0-nfs-custom-pvc-1-snapimport-1