apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: c1-svm0-nfs-zone1-sc
provisioner: csi.trident.netapp.io
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - zone1
  - key: topology.kubernetes.io/region
    values:
    - trident
parameters:
  backendType: ontap-nas
  storagePools: c1-svm0-nfs-zone1-tbe:.*