kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-import
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs-basic
