apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zone2-pvc
  namespace: topology
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: zone2-san