apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: zone2-san
provisioner: csi.trident.netapp.io
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - zone2
  - key: topology.kubernetes.io/region
    values:
    - trident
parameters:
  backendType: "ontap-san"