# apiVersion: v1
# kind: Secret
# metadata:
#   name: san-backend-secret
#   namespace: trident
# type: kubernetes.io/basic-auth
# stringData:
#   username: vsadmin
#   password: Netapp1!
# ---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: zone2-san-backend
  namespace: trident
spec:
  version: 1
  backendName: zone2-san
  storageDriverName: ontap-san
  managementLIF: 192.168.0.40
  dataLIF: 192.168.0.41
  svm: svm1
  storagePrefix: zone2_
  credentials:
    name: san-backend-secret
  supportedTopologies:
    - topology.kubernetes.io/region: trident
    - topology.kubernetes.io/zone: zone2


