apiVersion: v1
kind: Secret
metadata:
  name: zone1-nfs-backend-secret
  namespace: trident
type: kubernetes.io/basic-auth
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: c1-svm0-nfs-zone1-tbc
  namespace: trident
spec:
  version: 1
  backendName: c1-svm0-nfs-zone1-tbe
  storageDriverName: ontap-nas
  managementLIF: 192.168.0.30
  dataLIF: 192.168.0.31
  storagePrefix: zone1_
  credentials:
    name: zone1-nfs-backend-secret
  supportedTopologies:
    - topology.kubernetes.io/region: trident
    - topology.kubernetes.io/zone: zone1
