apiVersion: groupsnapshot.storage.k8s.io/v1beta1
kind: VolumeGroupSnapshot
metadata:
  name: c1-svm1-iscsi-groupa-snap-1
  namespace: default
spec:
  volumeGroupSnapshotClassName: change_me
  source:
    selector:
      matchLabels:
        consistentGroupSnapshot: change_me