apiVersion: v1
kind: Namespace
metadata:
  name: topology
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: c1-svm0-nfs-zone1-pvc-1
  namespace: topology
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: c1-svm0-nfs-zone1-sc