apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: c1-svm1-iscsi-zone2-pvc-1
  namespace: topology
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: c1-svm1-iscsi-zone2-sc