apiVersion: v1
kind: Pod
metadata:
  name: two-pod
  labels:
    app: web
spec:
  volumes:
  - name: change_me
    # add here
  containers:
  - name: first
    image: nginx:1.14.2
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: change_me
      mountPath: /usr/share/nginx/html
  - name: second
    image: debian:10.10
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: change_me
      mountPath: /pod-data
    command: ["/bin/sh"]
    args:
      - "-c"
      - >
        while true; do
          date >> /pod-data/index.html;
          printf 'Hello from the second container<br>' >> /pod-data/index.html;
          sleep 1;
        done