apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: nvme-backend
  namespace: trident
spec:
  version: 1
  backendName: ontap-nvme-backend
  storageDriverName: ontap-san-economy
  managementLIF: change_me
  dataLIF: change_me
  svm: change_me
  sanType: change_me
  useREST: change_me
  credentials:
    name: san-backend-secret