kind: Pod
apiVersion: v1
metadata:
  name: nvme-pod
  namespace: default
  labels:
    app: nvme-web
spec:
  volumes:
    - name: nvme-storage
      persistentVolumeClaim:
       claimName: change_me
  containers:
    - name: nvme-container
      image: nginx:1.25-alpine-slim
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nvme-storage