apiVersion: v1
kind: Secret
metadata:
  name: san-backend-secret
  namespace: trident
type: kubernetes.io/basic-auth
stringData:
  username: change_me
  password: change_me
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: san-backend
  namespace: trident
spec:
  version: 1
  backendName: ontap-san-backend
  storageDriverName: ontap-san
  managementLIF: change_me
  dataLIF: change_me
  svm: change_me
  credentials:
    name: san-backend-secret