kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: c1-svm0-nas-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: change_me