kind: Pod
apiVersion: v1
metadata:
  name: nfs-snap-pod
  labels:
    app: nfs-snap-web
spec:
  volumes:
    - name: nfs-storage
      persistentVolumeClaim:
       claimName: nfs-snap
  containers:
    - name: nfs-container
      image: nginx
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: nfs-storage