kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: san-import
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: san-basic
