kind: Pod
apiVersion: v1
metadata:
  name: san-import-pod
  labels:
    app: san-import-web
spec:
  volumes:
    - name: san-storage
      persistentVolumeClaim:
       claimName: san-import
  containers:
    - name: san-container
      image: nginx:1.25-alpine-slim
      imagePullPolicy: IfNotPresent
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: san-storage