apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: c1-svm1-iscsi-pvc-1-snap-1
spec:
  volumeSnapshotClassName: csi-snap-class
  source:
    persistentVolumeClaimName: c1-svm1-iscsi-pvc-1