apiVersion: v1
kind: ConfigMap
metadata:
  name: trident-protect-env-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tridentprotect.labels" . | nindent 4 }}
data:
  TRIDENT_PROTECT_REGISTRY: "{{ .Values.controller.image.registry }}"
  TRIDENT_PROTECT_TAG: "{{ .Values.controller.image.tag | default .Chart.AppVersion }}"
  TRIDENT_PROTECT_SECRET: "{{ .Values.tridentProtectSecret }}"
  TRIDENT_PROTECT_AUTOSUPPORT_URL: "{{ .Values.autoSupport.url }}"
  {{- with .Values.customLabels }}
  TRIDENT_PROTECT_LABELS: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.clusterName }}
  TRIDENT_PROTECT_CLUSTER_NAME: "{{ .Values.clusterName }}"
  {{- end }}
