apiVersion: apps/v1
kind: Deployment
metadata:
  name: trident-protect-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "tridentprotect.labels" . | nindent 4 }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app: controller.protect.trident.netapp.io
        {{- with .Values.customLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: kube-rbac-proxy
          image: "{{ .Values.rbacProxy.image.registry }}/{{ .Values.rbacProxy.image.repository }}:{{ .Values.rbacProxy.image.tag }}"
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=0
          ports:
            - containerPort: 8443
              name: https
              protocol: TCP
          resources:
            {{- toYaml .Values.rbacProxy.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.rbacProxy.securityContext | nindent 12 }}
        - name: manager
          command:
            - /manager
          args:
            - --leader-elect
            - --health-probe-bind-address=:8081
            - --metrics-bind-address=127.0.0.1:8080
          image: {{ include "tridentprotect.fullImage" . }}
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: trident-protect-env-config
          securityContext:
            {{- toYaml .Values.controller.securityContext | nindent 12 }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
      serviceAccountName: trident-protect-controller-manager
      terminationGracePeriodSeconds: 10
