apiVersion: v1
kind: Secret
metadata:
  name: ontap-cluster2-admin
  namespace: gateway-system
type: kubernetes.io/basic-auth
stringData:
  username: admin
  password: Netapp1!
---
apiVersion: v1
kind: Secret
metadata:
  name: ontap-svmdst-admin
  namespace: gateway-system
type: kubernetes.io/basic-auth
stringData:
  username: vsadmin
  password: Netapp1!
---
apiVersion: gateway.netapp.com/v1beta2
kind: StorageVirtualMachine
metadata:
  name: svmdst
  namespace: gateway-system
spec:
  svmName: svmdst
  svmDeletionPolicy: Delete # For training only
  clusterHost: 192.168.0.102
  debug: false
  aggregates:
  - name: Cluster2_01_FC_1
  - name: Cluster2_01_FC_2
  management:
    name: manage1
    ip: 192.168.0.50
    netmask: 255.255.255.0
    broadcastDomain: Default
    homeNode: Cluster2-01
  vsadminCredentials:
    name: ontap-svmdst-admin
    namespace: gateway-system
  clusterCredentials:
    name: ontap-cluster2-admin
    namespace: gateway-system
  nfs:
    enabled: true
    v3: true
    v4: true
    v41: true
    interfaces:
    - name: nfs1
      ip: 192.168.0.51
      netmask: 255.255.255.0
      broadcastDomain: Default
      homeNode: Cluster2-01
    export:
      name: default
      rules:
      - clients: 0.0.0.0/0
        protocols: any
        rw: any
        ro: any
        superuser: any
        anon:  "65534"
  iscsi:
    enabled: true
    alias: svmdst
    interfaces:
    - name: iscsi1
      ip: 192.168.0.52
      netmask: 255.255.255.0
      broadcastDomain: Default
      homeNode: Cluster2-01
    - name: iscsi2
      ip: 192.168.0.53
      netmask: 255.255.255.0
      broadcastDomain: Default
      homeNode: Cluster2-01