apiVersion: v1
kind: Pod
metadata:
  name: direct-nfs-pod
spec:
  containers:
  - image: debian:11.8-slim
    imagePullPolicy: IfNotPresent
    name: linux
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /opt/this
      name: nfsvol
  volumes:
  - name: nfsvol
    nfs:
      server: 192.168.0.31
      path: /nfs
      readOnly: false