apiVersion: v1
kind: Service
metadata:
  name: testvm-load
  namespace: testvm
  labels:
    kubevirt.io/vm: vm-cirros
spec:
  ports:
  - port: 22
    targetPort: 22
  selector:
    kubevirt.io/vm: vm-cirros
  type: LoadBalancer