apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  creationTimestamp: null
  name: mysqlapp-snaprestore1
  namespace: mysqlapp
spec:
  appArchivePath: change_me
  appVaultRef: c1-s3-src-appvault
  namespaceMapping:
  - destination: mysqlapp1
    source: mysqlapp
  resourceFilter: {}
---
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: mysqlapp1
  namespace: mysqlapp1
spec:
  includedNamespaces:
  - labelSelector: {}
    namespace: mysqlapp1