apiVersion: protect.trident.netapp.io/v1
kind: Snapshot
metadata:
  name: mysqlapp-snap-1
  namespace: mysqlapp
spec:
  appVaultRef: c1-svm0-s3-av
  applicationRef: mysqlapp
  completionTimeout: 0s
  volumeSnapshotsCreatedTimeout: 0s
  volumeSnapshotsReadyToUseTimeout: 0s
