apiVersion: protect.trident.netapp.io/v1
kind: SnapshotRestore
metadata:
  name: mysqlapp-snaprestore1
  namespace: mysqlapp1
spec:
  appArchivePath: change_me
  appVaultRef: c1-svmsrc-s3-av
  namespaceMapping:
  - source: mysqlapp
    destination: mysqlapp1
---
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: mysqlapp1
  namespace: mysqlapp1
spec:
  includedNamespaces:
  - labelSelector: {}
    namespace: mysqlapp1
