apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  name: mysqlapp-sched1-daily
  namespace: mysqlapp
spec:
  appVaultRef: c1-svmsrc-s3-av
  applicationRef: mysqlapp
  backupRetention: "3"
  dayOfMonth: ""
  dayOfWeek: ""
  enabled: true
  granularity: Daily
  hour: "17"
  minute: "30"
  snapshotRetention: "3"