apiVersion: protect.trident.netapp.io/v1
kind: BackupRestore
metadata:
  name: mysqlapp-backuprestore1
  namespace: mysqlapp2
spec:
  appArchivePath: change_me
  appVaultRef: c1-svmsrc-s3-av
  namespaceMapping:
  - source: mysqlapp
    destination: mysqlapp2
  destinationApplicationName: mysqlapp2    

