apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: testvm3
  namespace: testvm3
spec:
  domain:
    cpu:
      cores: 1
    devices:
      disks:
      - disk:
          bus: virtio
        name: dvdisk
      - cdrom:
          bus: sata
        name: cloudinitdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 128M
  terminationGracePeriodSeconds: 0
  volumes:
  - name: dvdisk
    dataVolume:
      name: dv-vmdk
  - name: cloudinitdisk
    cloudInitNoCloud:
      userDataBase64: SGkuXG4=
