apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-upload
spec:
  source:
      upload: {}
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: "250Mi"
