apiVersion: protect.trident.netapp.io/v1
kind: Schedule
metadata:
  name: myredisapp-sched2-5min
  namespace: myredisapp
spec:
  appVaultRef: c1-svmsrc-s3-av
  applicationRef: myredisapp
  backupRetention: "0"
  enabled: true
  granularity: Custom
  recurrenceRule: |-
    DTSTART:20220101T000200Z
    RRULE:FREQ=MINUTELY;INTERVAL=5
  snapshotRetention: "5"