apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: mywordpressapp-dst
  namespace: mywordpressapp-dst
spec:
  includedNamespaces:
  - labelSelector: {}
    namespace: mywordpressapp-dst